version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: notes_sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - notes_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_api
    environment:
      ConnectionStrings__Default: "Server=sqlserver;Database=NotesDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    
      ASPNETCORE_URLS: "http://+:80"

    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    networks:
      - notes_network

networks:
  notes_network:
    driver: bridge
